export const defaultProps = {
  scrollWholePage: true,
  noScrollbarGutters: false,
  fitContent: false,
  defaultTone: undefined as string | undefined,
  defaultTheme: undefined as string | undefined,
  autoDetectTone: false,
  persistTheme: false,
  toneStorageKey: "appTone",
  themeStorageKey: "appTheme",
  navPanelCollapseMode: "hidden" as "hidden" | "icons",
  persistNavPanel: false,
  navPanelStorageKey: "appNavPanel",
  navPanelPeek: false,
  navPanelResizable: false,
  navPanelMinWidth: 200,
  navPanelMaxWidth: 480,
};
